[bt-dualboot.src]
pypi = "bt-dualboot"

[bt-dualboot.fetch]
pypi = "bt-dualboot"

[csharp-ls.src]
github = "razzmatazz/csharp-language-server"

[csharp-ls.fetch]
url = "https://www.nuget.org/api/v2/package/csharp-ls/$ver"

[cups-brother-hll5100dn-lpr.src]
webpage = "https://support.brother.co.jp/j/b/downloadlist.aspx?c=jp&lang=ja&prod=hll5100dn&os=128"
regex = "[0-9]\\.[0-9]\\.[0-9]-[0-9]"

[cups-brother-hll5100dn-lpr.fetch]
url = "https://download.brother.com/welcome/dlf102553/hll5100dnlpr-$ver.i386.deb"

[cups-brother-hll5100dn-cupswrapper.src]
webpage = "https://support.brother.co.jp/j/b/downloadlist.aspx?c=jp&lang=ja&prod=hll5100dn&os=128"
regex = "[0-9]\\.[0-9]\\.[0-9]-[0-9]"

[cups-brother-hll5100dn-cupswrapper.fetch]
url = "https://download.brother.com/welcome/dlf102554/hll5100dncupswrapper-$ver.i386.deb"

[drbd9-dkms.src]
github_tag = "LINBIT/drbd"
include_regex = "drbd-9.1.*"
prefix = "drbd-"

[drbd9-dkms.fetch]
url = "https://pkg.linbit.com//downloads/drbd/9/drbd-$ver.tar.gz"

[droidcam-obs-plugin.src]
github = "dev47apps/droidcam-obs-plugin"

[droidcam-obs-plugin.fetch]
github = "dev47apps/droidcam-obs-plugin"

[julius-speech.src]
github_tag = "julius-speech/julius"

[julius-speech.fetch]
github = "julius-speech/julius"

[fence-agents.src]
github_tag = "ClusterLabs/fence-agents"

[fence-agents.fetch]
github = "ClusterLabs/fence-agents"

[knp.src]
git = "https://github.com/ku-nlp/knp/"

[knp.fetch]
github = "ku-nlp/knp"

[proton-ge-rtsp-bin.src]
github = "SpookySkeletons/proton-ge-rtsp"

[proton-ge-rtsp-bin.fetch]
tarball = "https://github.com/SpookySkeletons/proton-ge-rtsp/releases/download/GE-Proton9-22-rtsp17/GE-Proton9-22-rtsp17.tar.gz"

[ricoh-sp-c260series-ppd.src]
manual = "1.00"

[ricoh-sp-c260series-ppd.fetch]
url = "http://support.ricoh.com/w/bb/pub_j/dr_ut_d/4101035/4101035832/V100/5205252/sp-c260series-printer-1.00-amd64.deb"

[skk-emoji-jisyo.src]
github_tag = "uasi/skk-emoji-jisyo"

[skk-emoji-jisyo.fetch]
github = "uasi/skk-emoji-jisyo"

[emoticon-data.src]
git = "https://github.com/w33ble/emoticon-data"

[emoticon-data.fetch]
github = "w33ble/emoticon-data"

[snack.src]
regex = "Snack v[0-9]+\\.[0-9]+\\.[0-9]+"
webpage = "https://www.speech.kth.se/snack/"
prefix = "Snack v"

[snack.fetch]
url = "http://www.speech.kth.se/snack/dist/snack$ver.tar.gz"

[tkdnd.src]
github_tag = "petasis/tkdnd"
prefix = "tkdnd-release-test-v"

[tkdnd.fetch]
url = "https://github.com/petasis/tkdnd/archive/tkdnd-release-test-v$ver.tar.gz"

[wavesurfer.src]
httpheader = "http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz"
regex = "[0-9]+\\.[0-9]+\\.[0-9]+p[0-9]+"

[wavesurfer.fetch]
url = "http://downloads.sourceforge.net/wavesurfer/wavesurfer-$ver-src.tgz"

[vrchat-vpm-cli.src]
regex = "0\\.[0-9]+\\.[a-z0-9-.]+"
exclude_regex = ".*-alpha.*|.*-beta.*"
webpage = "https://www.nuget.org/packages/VRChat.VPM.CLI"

[vrchat-vpm-cli.fetch]
url = "https://www.nuget.org/api/v2/package/VRChat.VPM.CLI/$ver"

[virtualsmartcard.src]
github_tag = "frankmorgner/vsmartcard"
regex = "virtualsmartcard-*"

[virtualsmartcard.fetch]
github = "frankmorgner/vsmartcard"

[openpace.src]
github_tag = "frankmorgner/openpace"

[openpace.fetch]
github = "frankmorgner/openpace"

[yaskkserv2]
cargo_locks = ["Cargo.lock"]

[yaskkserv2.src]
github_tag = "wachikun/yaskkserv2"

[yaskkserv2.fetch]
github = "wachikun/yaskkserv2"

[jawiki-kana-kanji-dict.src]
git = "https://github.com/tokuhirom/jawiki-kana-kanji-dict.git"

[jawiki-kana-kanji-dict.fetch]
url = "https://raw.githubusercontent.com/tokuhirom/jawiki-kana-kanji-dict/$ver/SKK-JISYO.jawiki"

[zenn-cli.src]
github_tag = "zenn-dev/zenn-editor"
exclude_regex = ".*-alpha.*|.*-beta.*"

[zenn-cli.fetch]
url = "https://registry.npmjs.com/zenn-cli/-/zenn-cli-$ver.tgz"

[jupynium.src]
pypi = "jupynium"

[jupynium.fetch]
pypi = "jupynium"

[pyknp.src]
pypi = "pyknp"

[pyknp.fetch]
pypi = "pyknp"
