[bt-dualboot]
src.pypi = "bt-dualboot"
fetch.pypi = "bt-dualboot"

[csharp-ls]
src.github = "razzmatazz/csharp-language-server"
fetch.url = "https://www.nuget.org/api/v2/package/csharp-ls/$ver"

[cups-brother-hll5100dn-lpr]
src.webpage = "https://support.brother.co.jp/j/b/downloadlist.aspx?c=jp&lang=ja&prod=hll5100dn&os=128"
src.regex = "[0-9]\\.[0-9]\\.[0-9]-[0-9]"
fetch.url = "https://download.brother.com/welcome/dlf102553/hll5100dnlpr-$ver.i386.deb"

[cups-brother-hll5100dn-cupswrapper]
src.webpage = "https://support.brother.co.jp/j/b/downloadlist.aspx?c=jp&lang=ja&prod=hll5100dn&os=128"
src.regex = "[0-9]\\.[0-9]\\.[0-9]-[0-9]"
fetch.url = "https://download.brother.com/welcome/dlf102554/hll5100dncupswrapper-$ver.i386.deb"

[drbd9-dkms]
src.github_tag = "LINBIT/drbd"
src.include_regex = "drbd-9.1.*"
src.prefix = "drbd-"
fetch.url = "https://pkg.linbit.com//downloads/drbd/9/drbd-$ver.tar.gz"

[droidcam-obs-plugin]
src.github_tag = "dev47apps/droidcam-obs-plugin"
src.ignored = "2.2.1 2.3.0"
fetch.url = "https://github.com/dev47apps/droidcam-obs-plugin/releases/download/$ver/droidcam_obs_$ver_linux_ffmpeg5.zip"

# [fcitx5-mozc-ext-neologd]
# # src.git = "https://github.com/fcitx/mozc.git"
# src.manual = "1882e33b61673b66d63277f82b4c80ae4e506c10"
# fetch.github = "fcitx/mozc"
#
# [mozc-dict-jigyosyo]
# src.webpage = "https://osdn.net/projects-aur/ponsfoot-aur/storage/mozc/"
# src.regex = "jigyosyo-[0-9]+"
# src.prefix = "jigyosyo-"
# fetch.url = "https://osdn.net/projects-aur/ponsfoot-aur/storage/mozc/jigyosyo-$ver.zip"
#
# [mozc-dict-x-ken-all]
# src.webpage = "https://osdn.net/projects-aur/ponsfoot-aur/storage/mozc/"
# src.regex = "x-ken-all-[0-9]+"
# src.prefix = "x-ken-all-"
# fetch.url = "https://osdn.net/projects-aur/ponsfoot-aur/storage/mozc/x-ken-all-$ver.zip"
#
# [japanese-usege-dictionary]
# src.git = "https://github.com/hiroyuki-komatsu/japanese-usage-dictionary"
# fetch.git = "https://github.com/hiroyuki-komatsu/japanese-usage-dictionary"
#
# [mecab-ipadic-neologd]
# src.github = "neologd/mecab-ipadic-neologd"
# fetch.github = "neologd/mecab-ipadic-neologd"
#
# [mozcdict-ext]
# src.git = "https://github.com/reasonset/mozcdict-ext"
# fetch.git = "https://github.com/reasonset/mozcdict-ext"

[fence-agents]
src.github_tag = "ClusterLabs/fence-agents"
fetch.github = "ClusterLabs/fence-agents"

[knp]
src.git = "https://github.com/ku-nlp/knp/"
fetch.github = "ku-nlp/knp"

[plemoljp]
src.github = "yuru7/PlemolJP"
fetch.url = "https://github.com/yuru7/PlemolJP/releases/download/$ver/PlemolJP_$ver.zip"

[plemoljp-nf]
src.github = "yuru7/PlemolJP"
fetch.url = "https://github.com/yuru7/PlemolJP/releases/download/$ver/PlemolJP_NF_$ver.zip"

[plemoljp-hs]
src.github = "yuru7/PlemolJP"
fetch.url = "https://github.com/yuru7/PlemolJP/releases/download/$ver/PlemolJP_HS_$ver.zip"

[ricoh-sp-c260series-ppd]
src.manual = "1.00"
fetch.url = "http://support.ricoh.com/w/bb/pub_j/dr_ut_d/4101035/4101035832/V100/5205252/sp-c260series-printer-1.00-amd64.deb"

[skk-emoji-jisyo]
src.github_tag = "uasi/skk-emoji-jisyo"
fetch.github = "uasi/skk-emoji-jisyo"

[snack]
src.regex = "Snack v[0-9]+\\.[0-9]+\\.[0-9]+"
src.webpage = "https://www.speech.kth.se/snack/"
src.prefix = "Snack v"
fetch.url = "http://www.speech.kth.se/snack/dist/snack$ver.tar.gz"

[tkdnd]
src.github_tag = "petasis/tkdnd"
src.prefix = "tkdnd-release-test-v"
fetch.url = "https://github.com/petasis/tkdnd/archive/tkdnd-release-test-v$ver.tar.gz"

[wavesurfer]
src.httpheader = "http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz"
src.regex = "[0-9]+\\.[0-9]+\\.[0-9]+p[0-9]+"
fetch.url = "http://downloads.sourceforge.net/wavesurfer/wavesurfer-$ver-src.tgz"

[unityhub-latest]
src.aur = "unityhub"
fetch.url = "https://hub.unity3d.com/linux/repos/deb/pool/main/u/unity/unityhub_amd64/unityhub-amd64-$ver.deb"

[vrc-get-latest]
src.github_tag = "anatawa12/vrc-get"
src.exclude_regex = ".*-beta.*"
src.include_regex = "v1.5.*"
fetch.github = "anatawa12/vrc-get"
cargo_locks = ["Cargo.lock"]

[vrchat-vpm-cli]
src.regex = "0\\.[0-9]+\\.[0-9]+"
src.webpage = "https://www.nuget.org/packages/VRChat.VPM.CLI"
fetch.url = "https://www.nuget.org/api/v2/package/vrchat.vpm.cli/$ver"

[yaskkserv2]
src.github_tag = "wachikun/yaskkserv2"
fetch.github = "wachikun/yaskkserv2"
cargo_locks = ["Cargo.lock"]

[jawiki-kana-kanji-dict]
src.git = "https://github.com/tokuhirom/jawiki-kana-kanji-dict.git"
fetch.url = "https://raw.githubusercontent.com/tokuhirom/jawiki-kana-kanji-dict/$ver/SKK-JISYO.jawiki"

# python modules
[SpeechRecognition]
src.pypi = "SpeechRecognition"
fetch.pypi = "SpeechRecognition"

[doq]
src.pypi = "doq"
fetch.pypi = "doq"

[jupynium]
src.pypi = "jupynium"
fetch.pypi = "jupynium"

[suds]
src.pypi = "suds"
fetch.pypi = "suds"

[pyknp]
src.pypi = "pyknp"
fetch.pypi = "pyknp"
