[zotero-better-bibtex]
src.github_tag = "retorquere/zotero-better-bibtex"
src.prefix = "v"
src.exclude_regex = "v6.7.267|v7.0.77"
fetch.url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v$ver/zotero-better-bibtex-$ver.xpi"
[zotero-better-bibtex.passthru]
addonId = "better-bibtex@iris-advies.com"
description = "Make Zotero effective for us LaTeX holdouts"
homepage = "https://github.com/retorquere/zotero-better-bibtex"
license = "mit"

[zotero-zotfile]
src.github = "jlegewie/zotfile"
src.prefix = "v"
fetch.url = "https://github.com/jlegewie/zotfile/releases/download/v$ver/zotfile-$ver-fx.xpi"
[zotero-zotfile.passthru]
addonId = "zotfile@columbia.edu"
description = "Zotero plugin to manage your attachments: automatically rename, move, and attach PDFs (or other files) to Zotero items, sync PDFs from your Zotero library to your (mobile) PDF reader (e.g. an iPad, Android tablet, etc.), and extract PDF annotations."
homepage = "https://github.com/jlegewie/zotfile"
license = "gpl3"

[zotero-night]
src.github = "tefkah/zotero-night"
src.prefix = "v"
fetch.url = "https://github.com/tefkah/zotero-night/releases/download/v$ver/night.xpi"
[zotero-night.passthru]
addonId = "night@tefkah.com"
description = "Night theme for Zotero UI and PDF"
homepage = "https://github.com/tefkah/zotero"
license = "gpl3"

[zotero-pdf-translate]
src.github = "windingwind/zotero-pdf-translate"
src.prefix = "v"
fetch.url = "https://github.com/windingwind/zotero-pdf-translate/releases/download/v$ver/translate-for-zotero.xpi"
[zotero-pdf-translate.passthru]
addonId = "zoteropdftranslate@euclpts.com"
description = "Translate PDF, EPub, webpage, metadata, annotations, notes to the target language. Support 20+ translate services."
homepage = "https://github.com/winidngwind/zotero-pdf-translate"
license = "agpl3Only"

[zotero-reading-list]
src.github = "Dominic-DallOsto/zotero-reading-list"
src.prefix = "v"
fetch.url = "https://github.com/Dominic-DallOsto/zotero-reading-list/releases/download/v$ver/zotero-reading-list.xpi"
[zotero-reading-list.passthru]
addonId = "reading-list@hotmail.com"
description = "Keep track of whether you've read items in Zotero"
homepage = "https://github.com/Dominic-DallOsto/zotero-reading-list"
license = "gpl3"

[zotero-scipdf]
src.github = "syt2/zotero-scipdf"
src.prefix = "V"
fetch.url = "https://github.com/syt2/zotero-scipdf/releases/download/V$ver/sci-pdf.xpi"
[zotero-scipdf.passthru]
addonId = "scipdf@ytshen.com"
description = "Download PDF from Sci-Hub automatically (For Zotero7)"
homepage = "https://github.com/syt2/zotero-scipdf"
license = "agpl3Plus"

[zotero-zotmoov]
src.github = "wileyyugioh/zotmoov"
fetch.url = "https://github.com/wileyyugioh/zotmoov/releases/download/$ver/zotmoov-$ver-fx.xpi"
[zotero-zotmoov.passthru]
addonId = "zotmoov@wileyy.com"
description = "Mooves attachments and links them"
homepage = "https://github.com/wileyyugioh/zotmoov"
license = "gpl3Only"
